spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
    org.hibernate.SQL: debug